spring.h2.console.enabled: true
logging.level.org.hibernate.SQL: debug
server:
    port: 8080
        
spring: 
    main:
        banner-mode: "off"       
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=PostgreSQL
      
logging: 
    level: 
        org: 
            springframework: ERROR